import { useEffect, useRef, useState } from 'react'
import { models, modelAddress } from './models/modelRegistry'
import type { EngineMessage, Job, Progress } from './engine/protocol'
import { canvas, combine, decode, encode, pixels } from './engine/image'
import { guardSize } from './engine/tiles'
import { CACHE } from './engine/cache'
const BASE=new URL(import.meta.env.BASE_URL,location.origin).href
export default function App(){
 const [modelId,setModel]=useState('nomos-standard'),[scale,setScale]=useState<2|4>(4),[tile,setTile]=useState(0),[overlap,setOverlap]=useState(24),[backend,setBackend]=useState<'auto'|'wasm'>('auto')
 const [file,setFile]=useState<File>(),[source,setSource]=useState<HTMLImageElement>(),[preview,setPreview]=useState(''),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState<Progress>(),[error,setError]=useState(''),[detail,setDetail]=useState(''),[cached,setCached]=useState<string[]>([]),[gpu,setGpu]=useState('检测中'),[format,setFormat]=useState('image/png'),[quality,setQuality]=useState(.92),[split,setSplit]=useState(50),[zoom,setZoom]=useState(0),[metrics,setMetrics]=useState('')
 const worker=useRef<Worker|null>(null),cancelled=useRef(false),token=useRef(0),resultCanvas=useRef<HTMLCanvasElement|null>(null),urls=useRef<string[]>([]),viewport=useRef<HTMLDivElement>(null),pan=useRef<{x:number;y:number;left:number;top:number}|null>(null)
 const model=models.find(m=>m.id===modelId)!
 async function refreshCache(){try{const cache=await caches.open(CACHE);const keys=await cache.keys();setCached(keys.map(r=>r.url))}catch{setCached([])}}
 useEffect(()=>{void refreshCache();(async()=>{try{const nav=navigator as Navigator & {gpu?:{requestAdapter:()=>Promise<unknown>}};setGpu(await nav.gpu?.requestAdapter()?'WebGPU 可用':'CPU / WASM')}catch{setGpu('CPU / WASM')}})();return()=>{worker.current?.terminate();urls.current.forEach(URL.revokeObjectURL)}},[])
 function url(blob:Blob){const value=URL.createObjectURL(blob);urls.current.push(value);return value}
 function resetResult(){setResult('');setMetrics('');if(resultCanvas.current){resultCanvas.current.width=0;resultCanvas.current=null}}
 async function selectFile(f:File){if(busy)return;const version=++token.current;setError('');setDetail('');resetResult();setProgress(undefined)
  try{const image=await decode(f);if(version!==token.current)return;guardSize(image.naturalWidth,image.naturalHeight,model.scale);urls.current.forEach(URL.revokeObjectURL);urls.current=[];setFile(f);setSource(image);setPreview(url(f));setZoom(0)}catch(e){setError(String(e));setSource(undefined);setPreview('')}
 }
 useEffect(()=>{const handler=(e:ClipboardEvent)=>{const f=Array.from(e.clipboardData?.files??[]).find(f=>f.type.startsWith('image/'));if(f){e.preventDefault();void selectFile(f)}};window.addEventListener('paste',handler);return()=>window.removeEventListener('paste',handler)})
 async function sample(size:number){const c=canvas(size,size),ctx=c.getContext('2d')!;const gradient=ctx.createLinearGradient(0,0,size,size);gradient.addColorStop(0,'#b6cead');gradient.addColorStop(1,'#263b45');ctx.fillStyle=gradient;ctx.fillRect(0,0,size,size);ctx.fillStyle='#efd3a7';ctx.beginPath();ctx.arc(size*.48,size*.42,size*.27,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1c3035';ctx.font=`bold ${size*.16}px sans-serif`;ctx.fillText('BigImg',size*.17,size*.8);ctx.clearRect(0,0,5,5);const b=await encode(c,'image/png',1);await selectFile(new File([b],`sample-${size}.png`,{type:'image/png'}))}
 function cancel(){cancelled.current=true;token.current++;worker.current?.terminate();worker.current=null;setBusy(false);setProgress({stage:'已取消 · Cancelled',percent:0});void refreshCache()}
 async function start(){if(!source||!file)return;resetResult();setError('');setDetail('');setBusy(true);cancelled.current=false;const version=++token.current
  try{guardSize(source.naturalWidth,source.naturalHeight,model.scale)
   const job:Job={pixels:pixels(source),width:source.naturalWidth,height:source.naturalHeight,modelId,scale,tile,overlap,backend,baseUrl:BASE}
   const handle=async(message:EngineMessage)=>{if(version!==token.current)return
    if(message.type==='progress'){setProgress(old=>({...old,...message.value}));return}
    if(message.type==='error'){setError(message.message);setDetail(message.detail);setBusy(false);worker.current?.terminate();worker.current=null;return}
    try{setProgress(old=>({...old,stage:'Encoding · 编码图片',percent:100}));await new Promise(r=>setTimeout(r,0));if(version!==token.current)return
     const c=combine(message.pixels,message.width,message.height,source,scale);resultCanvas.current=c
     const b=await encode(c,format,quality);if(version!==token.current)return;setResult(url(b));setMetrics(`${source.naturalWidth} × ${source.naturalHeight} → ${c.width} × ${c.height} · ${message.backend} · Tile ${message.tile} · ${(message.ms/1000).toFixed(2)} s`);setProgress(old=>({...old,stage:'Done · 完成',percent:100}));setBusy(false);void refreshCache()
    }catch(e){setError('输出编码失败，请使用较小图片。');setDetail(String(e));setBusy(false)}finally{worker.current?.terminate();worker.current=null}
   }
   if(typeof Worker!=='undefined'){
    const w=new Worker(new URL('./engine/worker.ts',import.meta.url),{type:'module'});worker.current=w
    w.onmessage=e=>void handle(e.data);w.onerror=e=>{if(version===token.current){setError('推理 Worker 启动失败，请更新浏览器。');setDetail(e.message);setBusy(false);w.terminate()}}
    w.postMessage(job,[job.pixels.buffer])
   }else{const {run,readableError}=await import('./engine/run');try{await run(job,m=>void handle(m),()=>version!==token.current)}catch(e){await handle({type:'error',message:readableError(e),detail:String(e)})}}
  }catch(e){setError(String(e));setBusy(false)}
 }
 async function download(){if(!resultCanvas.current||!file)return;try{const b=await encode(resultCanvas.current,format,quality),ext=b.type.split('/')[1];const a=document.createElement('a');a.href=url(b);a.download=`${file.name.replace(/\.[^.]+$/,'')}_bigimg_${scale}x_${modelId}.${ext==='jpeg'?'jpg':ext}`;a.click()}catch(e){setError(String(e))}}
 return <><header><a className="brand" href={import.meta.env.BASE_URL}><span className="brand-icon">↗</span>BigImg<span className="tag">LOCAL AI</span></a><nav><a href="#models">模型与许可证</a><a href="https://github.com/zjjxwpstcnsm-gif/bigimg" target="_blank" rel="noreferrer">GitHub ↗</a></nav></header>
 <main><section className="hero"><div className="eyebrow"><span className="dot"/> FREE · PRIVATE · ON YOUR DEVICE</div><h1>让每一个细节，<br/><span>清晰可见。</span></h1><p>免费 AI 图片超分。图片不上传服务器，<br className="mobile-break"/>直接使用本机 GPU / CPU 处理。</p><div className="pills"><span>无需登录</span><span>原生 AI 模型</span><span>2× / 4× 分辨率</span></div></section>
 <section className="workspace"><div className="studio"><div className="panel-title"><span>01 / YOUR IMAGE</span><span className="device">● {progress?.backend??gpu}</span></div>
 {!preview?<label className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files[0])void selectFile(e.dataTransfer.files[0])}}><span className="upload-icon">↥</span><strong>拖入图片到这里</strong><span>或点击选择图片 · 支持粘贴</span><small>PNG、JPG、WebP · 透明背景可保留</small><input aria-label="选择图片" type="file" accept="image/*" disabled={busy} onChange={e=>{if(e.target.files?.[0])void selectFile(e.target.files[0])}}/></label>:<><div ref={viewport} className="viewport" onPointerDown={e=>{if(e.target instanceof HTMLInputElement)return;const v=viewport.current!;pan.current={x:e.clientX,y:e.clientY,left:v.scrollLeft,top:v.scrollTop};v.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!pan.current)return;viewport.current!.scrollLeft=pan.current.left+pan.current.x-e.clientX;viewport.current!.scrollTop=pan.current.top+pan.current.y-e.clientY}} onPointerUp={()=>pan.current=null} onPointerCancel={()=>pan.current=null}>
 <div className="comparison" style={{width:zoom?`${(resultCanvas.current?.width??source?.naturalWidth??1)*zoom}px`:'100%'}}><img draggable={false} src={result||preview} alt={result?'AI 超分结果':'原始图片'} />{result&&<img draggable={false} className="before" src={preview} alt="Before 原图" style={{clipPath:`inset(0 ${100-split}% 0 0)`}}/>}{result&&<><span className="badge before-label">BEFORE</span><span className="badge after-label">AFTER</span><div className="divider" style={{left:split+'%'}}/><input className="compare-range" aria-label="Before After 对比" type="range" min="0" max="100" value={split} onChange={e=>setSplit(Number(e.target.value))}/></>}</div></div>
 <div className="toolbar"><label className="button">更换图片<input aria-label="更换图片" type="file" accept="image/*" disabled={busy} onChange={e=>{if(e.target.files?.[0])void selectFile(e.target.files[0])}}/></label><div><button onClick={()=>setZoom(0)}>Fit</button><button onClick={()=>setZoom(1)}>100%</button><button aria-label="缩小" onClick={()=>setZoom(z=>Math.max(.25,(z||1)/1.5))}>−</button><button aria-label="放大" onClick={()=>setZoom(z=>Math.min(4,(z||1)*1.5))}>+</button></div></div></>}
 <div className="sample-row"><span>没有图片？试用本地生成样例</span><button disabled={busy} onClick={()=>void sample(64)}>64 × 64 ↗</button><button disabled={busy} onClick={()=>void sample(128)}>128 × 128 ↗</button></div>
 {source&&<div className="dimensions"><div><small>原尺寸</small><strong>{source.naturalWidth} × {source.naturalHeight}</strong></div><span>→</span><div><small>预计输出</small><strong>{source.naturalWidth*scale} × {source.naturalHeight*scale}</strong></div></div>}
 <div className="privacy">⌁ Your images stay on your device.<br/><span>图片只在本地浏览器中处理，不会上传到 BigImg 或其他服务器。</span></div>
 </div><aside><div className="panel-title"><span>02 / ENHANCE</span><span>AI Image Upscaler</span></div><fieldset disabled={busy}><label className="field">选择模型<select aria-label="选择模型" value={modelId} onChange={e=>{setModel(e.target.value);if(e.target.value==='realesrgan-x2')setScale(2);resetResult();setProgress(undefined)}}>{models.map(m=><option key={m.id} value={m.id}>{m.name} · {m.zhName}</option>)}</select></label><div className="model-card"><strong>{model.technicalName}</strong><p>{model.description}</p><div className="model-meta"><span>Native {model.scale}×</span><span>{(model.bytes/1048576).toFixed(1)} MiB</span><span>{cached.includes(modelAddress(model,BASE))?'Cached · 已缓存':'按需下载'}</span></div>{!model.commercialUse&&<p className="warning">Non-commercial model · 禁止商业用途</p>}{model.experimental&&<p className="warning">Experimental · 重型实验模型</p>}</div>
 <label className="field">输出倍率<select aria-label="输出倍率" value={scale} onChange={e=>{setScale(Number(e.target.value) as 2|4);resetResult()}}><option value="2">2×</option><option value="4" disabled={model.scale===2}>4×</option></select></label><small className="scale-note">{scale===model.scale?`Native ${scale}× · 原生超分`:'AI 4× → downsample to 2× · 高质量缩小'}</small>
 <details className="advanced"><summary>高级设置 <span>Tile / Backend</span></summary><div className="two-fields"><label className="field">Tile<select aria-label="Tile" value={tile} onChange={e=>setTile(Number(e.target.value))}>{[0,64,96,128,192,256].map(n=><option key={n} value={n}>{n||'Auto'}</option>)}</select></label><label className="field">Overlap<select aria-label="Overlap" value={overlap} onChange={e=>setOverlap(Number(e.target.value))}>{[16,24,32].map(n=><option key={n}>{n}</option>)}</select></label></div><label className="field">Acceleration<select aria-label="Acceleration" value={backend} onChange={e=>setBackend(e.target.value as 'auto'|'wasm')}><option value="auto">Auto · 优先 WebGPU</option><option value="wasm">CPU / WASM</option></select></label><small>内存不足自动减小 Tile。CPU 运行大型模型可能较慢。</small></details></fieldset>
 <button className="primary" disabled={!source||busy} onClick={()=>void start()}>开始 AI 超分 <span>↗</span></button>{busy&&<button className="cancel" onClick={cancel}>取消 · Cancel</button>}
 {progress&&<div className="progress" role="status"><strong>{progress.stage}</strong><progress max="100" value={progress.percent}/><div><span>{progress.processed??0} / {progress.total??'—'} Tiles</span><span>{Math.round(progress.percent)}%</span></div><small>{progress.backend} {progress.tile?`· Tile ${progress.tile}`:''}</small>{progress.note&&<p>{progress.note}</p>}</div>}
 {error&&<div className="error" role="alert">{error}{detail&&<details><summary>错误详情</summary><pre>{detail}</pre></details>}</div>}
 {result&&<div className="export"><h3>清晰，就现在。</h3><p data-testid="metrics">{metrics}</p><div className="two-fields"><label className="field">格式<select aria-label="输出格式" value={format} onChange={e=>setFormat(e.target.value)}><option value="image/png">PNG · 透明</option><option value="image/jpeg">JPEG · 白底</option><option value="image/webp">WebP</option></select></label><label className="field">Quality<input aria-label="Quality" type="number" min="10" max="100" value={Math.round(quality*100)} onChange={e=>setQuality(Math.max(.1,Math.min(1,Number(e.target.value)/100)))}/></label></div><button className="primary" onClick={()=>void download()}>下载图片 ↓</button></div>}
 </aside></section>
 <section className="guide"><div><span>01</span><h3>选一张图片</h3><p>照片、AI 真人、COS 或插画，<br/>都从你的设备开始。</p></div><div><span>02</span><h3>选择合适的细节</h3><p>自然人像选 Natural / Realistic；<br/>压缩图片选 Restore。</p></div><div><span>03</span><h3>放大，保留本来面貌</h3><p>真实超分网络恢复纹理，<br/>不默认添加换脸或人脸重绘。</p></div></section>
 <section id="models" className="licenses"><div className="section-heading"><div className="eyebrow">TRANSPARENT BY DESIGN</div><h2>模型与许可证</h2><p>每个选项对应独立权重。模型许可不等于图片版权许可。</p></div><div className="table-scroll"><table><thead><tr><th>模型 / 作者</th><th>架构</th><th>License</th><th>Commercial use</th><th>来源</th></tr></thead><tbody>{models.map(m=><tr key={m.id}><td><strong>{m.technicalName}</strong><br/><small>{m.author} · Attribution required</small></td><td>{m.architecture} · {m.scale}×</td><td><a href={m.licenseUrl} target="_blank" rel="noreferrer">{m.license}</a></td><td>{m.commercialUse?'允许，遵守许可':'禁止商业用途'}</td><td><a href={m.sourceUrl} target="_blank" rel="noreferrer">Source ↗</a></td></tr>)}</tbody></table></div><p className="license-note">ClearReality 使用作者当前 Apache-2.0 ONNX 发行版。所有权重版本及 SHA-256 固定；实验记录见 GitHub 文档。首次使用下载模型，后续优先读取本机缓存。</p><button disabled={busy} onClick={async()=>{try{await caches.delete(CACHE);await refreshCache()}catch(e){setError('无法清理缓存：'+String(e))}}}>清理模型缓存</button></section>
 </main><footer><span className="brand">↗ BigImg</span><span>Free. Private. Runs on your device.</span><a href="https://github.com/zjjxwpstcnsm-gif/bigimg">开源代码 ↗</a></footer></>
}
